version: "3.9"
services:
  db:
    image: mongo:6.0-focal
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kpsing
      - MONGO_INITDB_ROOT_PASSWORD=passw0rd
      - MONGO_INITDB_DATABASE=node-ts
    ports:
      - 27017:27017
    volumes:
      - ./_data:/data/db
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passw0rd
      ME_CONFIG_MONGODB_URL: mongodb://kpsing:passw0rd@db:27017/